dragon.plugin.version=1.1.63
dragon.artifact.base=DragonGestion
dragon.artifact.name=DragonGestion-1.1.63
dragon.output.dir=C:\Users\AZ\Documents\Plugin\1.21.8\DragonGestion\versions\DragonGestion-1.1.63
dragon.output.file=C:\Users\AZ\Documents\Plugin\1.21.8\DragonGestion\versions\DragonGestion-1.1.63\DragonGestion-1.1.63.jar
